name: Checks

on:
  pull_request_target:
    branches: ['main']

  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 21
      - name: Install Dependencies
        run: npm install
      - name: Checks
        run: npm run check
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 21
      - name: Install Dependencies
        run: npm install
      - name: Lint
        run: npm run lint
